"""empty message

Revision ID: 83feb96611fb
Revises: 66e0864df37a
Create Date: 2022-01-24 19:15:31.516534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83feb96611fb'
down_revision = '66e0864df37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
